const IMAGE_CATEGORY_ALIASES = {
  emergency: ['national emergency', 'emergency response support system'], police: ['police'], fire: ['fire'], ambulance: ['ambulance', 'medical'], cyberCrime: ['cyber crime', 'cybercrime', 'cyber'], lpg: ['lpg leak', 'lpg'], road: ['road accident', 'accident'], disaster: ['disaster management', 'disaster', 'ndrf', 'flood', 'earthquake'], women: ['women', 'woman'], child: ['child', 'children', 'childline'], ncw: ['national commission for women'], senior: ['senior citizen', 'elderline'], disability: ['persons with disabilities', 'disabilities'], railway: ['railway', 'train', 'rail'], uidai: ['uidai', 'aadhaar'], consumer: ['consumer'], tourist: ['tourist'], health: ['health mission', 'health'], ragging: ['anti ragging', 'ragging'], humanRights: ['human rights'], narcotics: ['narcotics', 'manas']
};
const SOURCE = { india: 'India.gov.in', mha: 'Ministry of Home Affairs', cyber: 'National Cyber Crime Reporting Portal', ndrf: 'National Disaster Response Force', official: 'Relevant official government service' };
const HELPLINES = [
 {id:'112',category:'emergency',service:'National Emergency Number',organization:'Emergency Response Support System (ERSS)',number:'112',telNumber:'112',description:'Police, fire, health/ambulance and other emergency response needs.',priority:'CRITICAL',keywords:['national emergency','unified emergency','police fire health'],imageCategory:'emergency',source:SOURCE.mha,note:'112 is the nationwide unified emergency number and should be used for immediate emergencies.'},
 {id:'100',category:'police',service:'Police',organization:'Police Emergency Helpline',number:'100',telNumber:'100',description:'Police emergencies.',priority:'CRITICAL',keywords:['police emergency'],imageCategory:'police',source:SOURCE.mha},
 {id:'101',category:'fire',service:'Fire',organization:'Fire Services / Fire Brigade',number:'101',telNumber:'101',description:'Fire emergencies.',priority:'CRITICAL',keywords:['fire brigade service'],imageCategory:'fire',source:SOURCE.mha},
 {id:'102',category:'medical',service:'Ambulance',organization:'National Ambulance Service',number:'102',telNumber:'102',description:'Ambulance / medical transport assistance.',priority:'CRITICAL',keywords:['medical health'],imageCategory:'ambulance',source:SOURCE.mha},
 {id:'1930',category:'cyber',service:'Cyber Crime',organization:'National Cyber Crime Helpline / I4C',number:'1930',telNumber:'1930',description:'Cybercrime and financial cyber fraud reporting.',priority:'HIGH',keywords:['cyber fraud financial complaint'],imageCategory:'cyberCrime',source:SOURCE.cyber,note:'Cybercrime complaints can also be filed through the official National Cyber Crime Reporting Portal.'},
 {id:'1906',category:'emergency',service:'LPG Leak',organization:'LPG Emergency Helpline',number:'1906',telNumber:'1906',description:'LPG leakage emergencies.',priority:'CRITICAL',keywords:['gas leak cooking gas'],imageCategory:'lpg',source:SOURCE.mha},
 {id:'1073',category:'emergency',service:'Road Accident',organization:'Road Accident Helpline',number:'1073',telNumber:'1073',description:'Road accident assistance.',priority:'CRITICAL',keywords:['highway crash road'],imageCategory:'road',source:SOURCE.mha},
 {id:'1070',category:'disaster',service:'Disaster Management',organization:'Relief Commissioner / Natural Calamities',number:'1070',telNumber:'1070',description:'Natural calamity-related assistance.',priority:'CRITICAL',keywords:['flood earthquake calamity'],imageCategory:'disaster',source:SOURCE.mha},
 {id:'011-24363260',category:'disaster',service:'NDRF / Earthquake / Flood / Disaster',organization:'National Disaster Response / NDRF-related assistance',number:'011-24363260',telNumber:'01124363260',description:'Disaster-related assistance.',priority:'HIGH',keywords:['ndrf flood earthquake'],imageCategory:'disaster',source:SOURCE.ndrf},
 {id:'181',category:'women',service:'Women Helpline',organization:'Women Helpline',number:'181',telNumber:'181',description:'Women in distress and support services.',priority:'HIGH',keywords:['woman distress support'],imageCategory:'women',source:SOURCE.india},
 {id:'1098',category:'children',service:'Child Helpline',organization:'Child Helpline',number:'1098',telNumber:'1098',description:'Children in distress, danger, or requiring assistance.',priority:'CRITICAL',keywords:['child children danger distress'],imageCategory:'child',source:SOURCE.india},
 {id:'7827170170',category:'women',service:'National Commission for Women',organization:'National Commission for Women (NCW)',number:'7827170170',telNumber:'7827170170',description:'Women’s rights grievances and complaints involving harassment or violence.',priority:'HIGH',keywords:['ncw rights harassment violence'],imageCategory:'ncw',source:SOURCE.india},
 {id:'14567',category:'vulnerable',service:'Senior Citizens Helpline',organization:'Elderline / Senior Citizens Helpline',number:'14567',telNumber:'14567',description:'Support involving senior citizens, including assistance, legal aid, protection from abuse, and rescue.',priority:'HIGH',keywords:['elderly elderline abuse legal aid'],imageCategory:'senior',source:SOURCE.india},
 {id:'14456',category:'vulnerable',service:'Persons with Disabilities Helpline',organization:'Department of Empowerment of Persons with Disabilities',number:'14456',telNumber:'14456',description:'Support and assistance for persons with disabilities.',priority:'HIGH',keywords:['disability assistance pwd'],imageCategory:'disability',source:SOURCE.india},
 {id:'139',category:'railway',service:'Indian Railways',organization:'Indian Railways',number:'139',telNumber:'139',description:'Railway-related assistance, enquiries, complaints and support.',priority:'HIGH',keywords:['train rail travel enquiry complaint'],imageCategory:'railway',source:SOURCE.india},
 {id:'1947',category:'public',service:'UIDAI',organization:'UIDAI',number:'1947',telNumber:'1947',description:'Aadhaar-related assistance.',priority:'NORMAL',keywords:['aadhaar identity'],imageCategory:'uidai',source:SOURCE.india},
 {id:'1915',category:'public',service:'National Consumer Helpline',organization:'National Consumer Helpline',number:'1915',telNumber:'1915',description:'Consumer complaints and assistance.',priority:'NORMAL',keywords:['consumer complaint'],imageCategory:'consumer',source:SOURCE.india},
 {id:'1363',category:'public',service:'Tourist Helpline',organization:'Ministry of Tourism / Tourist Helpline',number:'1363',telNumber:'1363',description:'Tourist assistance.',priority:'NORMAL',keywords:['tourism travel visitor'],imageCategory:'tourist',source:SOURCE.india},
 {id:'104',category:'medical',service:'National Health Mission',organization:'National Health Mission',number:'104',telNumber:'104',description:'Health-related assistance where the service is available.',priority:'HIGH',keywords:['health medical'],imageCategory:'health',source:SOURCE.india},
 {id:'1800-180-5522',category:'public',service:'National Anti-Ragging Helpline',organization:'National Anti-Ragging Helpline',number:'1800-180-5522',telNumber:'18001805522',description:'Reporting/support regarding ragging in educational institutions.',priority:'HIGH',keywords:['student college education'],imageCategory:'ragging',source:SOURCE.india},
 {id:'14433',category:'public',service:'National Human Rights Commission',organization:'National Human Rights Commission',number:'14433',telNumber:'14433',description:'Human-rights-related complaints and assistance.',priority:'HIGH',keywords:['rights complaint legal'],imageCategory:'humanRights',source:SOURCE.india},
 {id:'1933',category:'public',service:'National Narcotics Helpline / MANAS',organization:'National Narcotics Helpline (MANAS)',number:'1933',telNumber:'1933',description:'Drug-related assistance/reporting.',priority:'HIGH',keywords:['drug narcotics substance'],imageCategory:'narcotics',source:SOURCE.mha}
];
const FILTERS = [['all','ALL'],['emergency','EMERGENCY'],['police','POLICE'],['medical','MEDICAL'],['fire','FIRE'],['women','WOMEN'],['children','CHILDREN'],['cyber','CYBER'],['disaster','DISASTER'],['railway','RAILWAY'],['public','PUBLIC SERVICES'],['vulnerable','VULNERABLE PERSONS']];
const imageFiles = ['Ambulance.jpg','Child Helpline.jpg','Cyber Crime.jpg','Disaster Management.jpg','Fire.jpg','indian railways.jpg','LPG Leak.jpg','National Anti-Ragging Helpline.jpg','National Commission for Women.jpg','national consumer helpline.jpg','National Emergency Number  Emergency Response Support System.jpg','National Health Mission.jpg','National Narcotics Helpline  MANAS.jpg','Persons with Disabilities Helpline.jpg','Police.jpg','Road Accident.jpg','Senior Citizens Helpline.jpg','tourist helpline.jpg','UIDAI.jpg','Women Helpline.jpg'];
const normalize = value => value.toLowerCase().replace(/\.[^.]+$/, '').replace(/[-_]+/g,' ').replace(/\s+/g,' ').trim();
function getMatchingImage(service) { const aliases = IMAGE_CATEGORY_ALIASES[service.imageCategory] || []; const names = imageFiles.map(file => ({file, name:normalize(file)})); const exact = names.find(item => item.name === normalize(service.service)); const match = exact || names.find(item => aliases.some(alias => item.name.includes(normalize(alias)))); return match ? `assets/helplines/${encodeURIComponent(match.file).replace(/%2F/g, '/')}` : null; }
const grid = document.querySelector('#helpline-grid'); const filters = document.querySelector('#filters'); const search = document.querySelector('#search-input'); const count = document.querySelector('#result-count'); const empty = document.querySelector('#empty-state'); let activeFilter = 'all'; let emergencyMode = false;
filters.innerHTML = FILTERS.map(([id,label], index) => `<button class="filter ${index === 0 ? 'active' : ''}" type="button" data-filter="${id}" aria-pressed="${index === 0}">${label}</button>`).join('');
function iconFor(category) { return ({police:'✦',fire:'△',medical:'✚',cyber:'⌁',disaster:'⌁',women:'◌',children:'♧',railway:'▤',public:'▣',vulnerable:'◇',emergency:'◉'}[category] || '＋'); }
function cardTemplate(item, index) { const image = getMatchingImage(item); return `<article class="card priority-${item.priority.toLowerCase()}" data-id="${item.id}" style="--delay:${Math.min(index,10) * 35}ms"><div class="card-top"><span class="category-icon" aria-hidden="true">${iconFor(item.category)}</span>${image ? `<img class="sticker" src="${image}" alt="${item.service} sticker" data-fallback="${iconFor(item.category)}">` : `<span class="sticker fallback" aria-hidden="true">${iconFor(item.category)}</span>`}<span class="priority-label"><i></i>${item.priority}${item.priority === 'CRITICAL' ? ' / URGENT' : ''}</span></div><div class="card-content"><p class="card-category">${item.category.toUpperCase()} / ${item.id === '112' ? 'PRIMARY LINE' : 'NATIONAL SERVICE'}</p><h3>${item.service}</h3><p class="organization">${item.organization}</p><a class="card-number" href="tel:${item.telNumber}" aria-label="Call ${item.service}, ${item.number}">${item.number}</a><p class="description">${item.description}</p></div><div class="card-actions"><a class="call-link" href="tel:${item.telNumber}">CALL <span aria-hidden="true">↗</span></a><button class="copy-button" type="button" data-number="${item.number}">COPY NUMBER</button><button class="details-button" type="button" data-details="${item.id}">DETAILS <span aria-hidden="true">+</span></button></div></article>`; }
function render() { const query = normalize(search.value); const visible = HELPLINES.filter(item => (activeFilter === 'all' || item.category === activeFilter || (activeFilter === 'emergency' && item.priority === 'CRITICAL')) && (!query || normalize([item.service,item.organization,item.number,item.category,...item.keywords].join(' ')).includes(query))); grid.innerHTML = visible.map(cardTemplate).join(''); count.textContent = `${visible.length} service${visible.length === 1 ? '' : 's'}`; empty.hidden = visible.length > 0; if (emergencyMode) document.querySelectorAll('.card').forEach(card => card.classList.toggle('emergency-priority', ['112','100','101','102'].includes(card.dataset.id))); }
function showToast(text = 'NUMBER COPIED') { const toast = document.querySelector('#toast'); toast.textContent = text; toast.classList.add('show'); clearTimeout(showToast.timer); showToast.timer = setTimeout(() => toast.classList.remove('show'), 1800); }
function showDetails(id) { const item = HELPLINES.find(entry => entry.id === id); if (!item) return; document.querySelector('#modal-title').textContent = item.service; document.querySelector('#modal-number').textContent = item.number; document.querySelector('#modal-org').textContent = item.organization; document.querySelector('#modal-description').textContent = item.description; document.querySelector('#modal-note').textContent = item.note || 'Use this line only for the situation described above. For immediate emergencies, call 112.'; document.querySelector('#modal-source').textContent = item.source; const call = document.querySelector('#modal-call'); call.href = `tel:${item.telNumber}`; document.querySelector('#details-modal').showModal(); }
filters.addEventListener('click', event => { const button = event.target.closest('[data-filter]'); if (!button) return; activeFilter = button.dataset.filter; filters.querySelectorAll('.filter').forEach(item => { const active = item === button; item.classList.toggle('active', active); item.setAttribute('aria-pressed', active); }); render(); });
search.addEventListener('input', render); document.querySelector('#clear-search').addEventListener('click', () => { search.value = ''; activeFilter = 'all'; filters.querySelectorAll('.filter').forEach((item,index) => { const active = index === 0; item.classList.toggle('active', active); item.setAttribute('aria-pressed', active); }); render(); search.focus(); });
grid.addEventListener('click', event => { const copy = event.target.closest('.copy-button'); const details = event.target.closest('[data-details]'); if (copy) { if (navigator.clipboard) navigator.clipboard.writeText(copy.dataset.number).then(() => showToast()).catch(() => showToast('SELECT NUMBER TO COPY')); else showToast('SELECT NUMBER TO COPY'); copy.classList.add('copied'); setTimeout(() => copy.classList.remove('copied'), 1200); } if (details) showDetails(details.dataset.details); });
document.querySelector('#close-modal').addEventListener('click', () => document.querySelector('#details-modal').close()); document.querySelector('#details-modal').addEventListener('click', event => { if (event.target.id === 'details-modal') event.target.close(); });
document.querySelector('#mode-toggle').addEventListener('click', event => { emergencyMode = !emergencyMode; document.body.classList.toggle('emergency-mode', emergencyMode); event.currentTarget.setAttribute('aria-pressed', emergencyMode); event.currentTarget.innerHTML = emergencyMode ? '<span aria-hidden="true">×</span> Exit emergency mode' : '<span aria-hidden="true">◉</span> Emergency mode'; if (emergencyMode) { activeFilter = 'emergency'; filters.querySelectorAll('.filter').forEach(item => { const active = item.dataset.filter === 'emergency'; item.classList.toggle('active', active); item.setAttribute('aria-pressed', active); }); document.querySelector('#directory-title').textContent = 'Emergency lines.'; } else { activeFilter = 'all'; filters.querySelectorAll('.filter').forEach((item,index) => { const active = index === 0; item.classList.toggle('active', active); item.setAttribute('aria-pressed', active); }); document.querySelector('#directory-title').textContent = 'Find the right line.'; } render(); window.scrollTo({top: document.querySelector('.directory').offsetTop - 20, behavior:'smooth'}); });
document.addEventListener('keydown', event => { if (event.key === '/' && document.activeElement !== search && document.activeElement.tagName !== 'INPUT') { event.preventDefault(); search.focus(); } if (event.key === 'Escape' && document.querySelector('#details-modal').open) document.querySelector('#details-modal').close(); });
document.addEventListener('error', event => { if (event.target.matches('.sticker')) { const fallback = document.createElement('span'); fallback.className = 'sticker fallback'; fallback.setAttribute('aria-hidden','true'); fallback.textContent = event.target.dataset.fallback; event.target.replaceWith(fallback); } }, true);
render();
